
// This file is auto-generated by the API. Do not edit directly.
import locationsData from '../../../.data/locations.json';

export interface Location {
  id: string;
  name: string;
  value: string;
}

export const locations: Location[] = locationsData;
