// This file is auto-generated by the API. Do not edit directly.

interface Category {
  id: string;
  name: string;
  price: number;
  validity: string;
  capacity: string;
}

interface Network {
  id: string;
  name: string;
  logo?: string;
  address?: string;
  ownerPhone?: string;
  categories: Category[];
}

export const networks: Network[] = [
  {
    "id": "new-network-1763067922593",
    "name": "شبكة ببحم",
    "logo": "",
    "address": "مديرية شبام",
    "ownerPhone": "",
    "categories": []
  },
  {
    "id": "new-network-1763068099085",
    "name": "شبكة ببحم",
    "logo": "",
    "address": "مديرية شبام",
    "ownerPhone": "",
    "categories": []
  },
  {
    "id": "new-network-1763069042842",
    "name": "شبكة ببحم",
    "logo": "",
    "address": "مديرية شبام",
    "ownerPhone": "",
    "categories": [
      {
        "id": "new-cat-1763069053708",
        "name": "",
        "price": 0,
        "validity": "",
        "capacity": ""
      }
    ]
  },
  {
    "id": "new-network-1763069353286",
    "name": "شبكة بيحم",
    "logo": "",
    "address": "شبام",
    "ownerPhone": "",
    "categories": []
  },
  {
    "id": "network-1763069797774",
    "name": "شبكة بيحم",
    "address": "مديرية شبام",
    "logo": "",
    "ownerPhone": "773108411",
    "categories": []
  }
];