
// This file is auto-generated by the API. Do not edit directly.

interface Category {
  id: string;
  name: string;
  price: number;
  validity: string;
  capacity: string;
}

interface Network {
  id: string;
  name: string;
  logo?: string;
  address?: string;
  categories: Category[];
}

export const networks: Network[] = [
  {
    "id": "new-network-1763045686448",
    "name": "شبكة الخير",
    "logo": "",
    "categories": [],
    "address": "مديرية شبام"
  },
  {
    "id": "new-network-1763045695800",
    "name": "شبكة بيحم",
    "logo": "",
    "categories": [],
    "address": "مديرية شبام"
  },
  {
    "id": "new-network-1763045702867",
    "name": "شبكة وناسة",
    "logo": "",
    "categories": [],
    "address": "مديرية شبام"
  },
  {
    "id": "new-network-1763045714395",
    "name": "شبكة الرشيدي",
    "logo": "",
    "categories": [],
    "address": "مديرية شبام"
  },
  {
    "id": "new-network-1763045723224",
    "name": "شبكة الدار",
    "logo": "",
    "categories": [],
    "address": "مديرية شبام"
  }
];
