
// This file is auto-generated by the API. Do not edit directly.

export interface PaymentMethod {
  id: string;
  name: string;
  description: string;
  accountName: string;
  accountNumber: string;
  logoUrl?: string; // The URL for the payment method's logo
  theme: {
    iconBg: string;
    iconColor: string;
    borderColor: string;
  };
}

export const paymentMethods: PaymentMethod[] = [
  {
    "id": "kareemi",
    "name": "خدمة حاسب | بنك الكريمي",
    "description": "تحويل بنكي عبر حاسب",
    "accountName": "تطبيق كرتي ",
    "accountNumber": "1055518",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-purple-100 dark:bg-purple-900/50",
      "iconColor": "text-purple-600 dark:text-purple-400",
      "borderColor": "border-purple-500"
    }
  },
  {
    "id": "amqi",
    "name": "شركة العمقي للصرافة",
    "description": "تحويل عبر العمقي",
    "accountName": "محمد راضي ربيع باشادي ",
    "accountNumber": "2345678",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-green-100 dark:bg-green-900/50",
      "iconColor": "text-green-600 dark:text-green-400",
      "borderColor": "border-green-500"
    }
  },
  {
    "id": "busairi",
    "name": "بي كاش - بنك الكريمي",
    "description": "تحويل عبر بي كاش",
    "accountName": "تطبيق كرتي",
    "accountNumber": "3456789",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-blue-100 dark:bg-blue-900/50",
      "iconColor": "text-blue-600 dark:text-blue-400",
      "borderColor": "border-blue-500"
    }
  }
];

