
// This file is auto-generated by the API. Do not edit directly.

export interface PaymentMethod {
  id: string;
  name: string;
  description: string;
  accountName: string;
  accountNumber: string;
  logoUrl?: string; // The URL for the payment method's logo
  theme: {
    iconBg: string;
    iconColor: string;
    borderColor: string;
  };
}

export const paymentMethods: PaymentMethod[] = [
  {
    "id": "kareemi",
    "name": "خدمة حاسب | بنك الكريمي",
    "description": "تحويل بنكي عبر حاسب",
    "accountName": "تطبيق كرتي ",
    "accountNumber": "1055518",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-primary/10",
      "iconColor": "text-primary",
      "borderColor": "border-primary"
    }
  },
  {
    "id": "amqi",
    "name": "شركة العمقي للصرافة",
    "description": "تحويل عبر العمقي",
    "accountName": "محمد راضي ربيع باشادي ",
    "accountNumber": "2345678",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-primary/10",
      "iconColor": "text-primary",
      "borderColor": "border-primary"
    }
  },
  {
    "id": "busairi",
    "name": "بي كاش - بنك البسيري",
    "description": "تحويل عبر بي كاش",
    "accountName": "تطبيق كرتي",
    "accountNumber": "3456789",
    "logoUrl": "",
    "theme": {
      "iconBg": "bg-primary/10",
      "iconColor": "text-primary",
      "borderColor": "border-primary"
    }
  }
];
