
import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    const paymentMethods = data.paymentMethods;

    if (!paymentMethods) {
      return NextResponse.json({ message: 'بيانات طرق الدفع مفقودة' }, { status: 400 });
    }

    const filePath = path.join(process.cwd(), 'src', 'lib', 'payment-methods.ts');
    
    // Construct the TypeScript file content
    const fileContent = `
// This file is auto-generated by the API. Do not edit directly.

export interface PaymentMethod {
  id: string;
  name: string;
  description: string;
  accountName: string;
  accountNumber: string;
  logoUrl?: string; // The URL for the payment method's logo
  theme: {
    iconBg: string;
    iconColor: string;
    borderColor: string;
  };
}

export const paymentMethods: PaymentMethod[] = ${JSON.stringify(paymentMethods, null, 2)};
`;

    fs.writeFileSync(filePath, fileContent.trim(), 'utf-8');

    return NextResponse.json({ message: 'تم حفظ طرق الدفع بنجاح.' }, { status: 200 });
  } catch (error) {
    console.error('فشل حفظ طرق الدفع:', error);
    return NextResponse.json({ message: 'حدث خطأ أثناء حفظ الملف' }, { status: 500 });
  }
}

